// <auto-generated />
using System;
using DetectiveAgencyProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Detective.Migrations
{
    [DbContext(typeof(DetectiveAgencyDbContext))]
    [Migration("20241007152922_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DetectiveAgencyProject.Models.Agency", b =>
                {
                    b.Property<int>("AgencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgencyId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AgencyId");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("DetectiveAgencyProject.Models.Case", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientId1")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DetectiveId")
                        .HasColumnType("int");

                    b.Property<int?>("DetectiveId1")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CaseId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientId1");

                    b.HasIndex("DetectiveId");

                    b.HasIndex("DetectiveId1");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("DetectiveAgencyProject.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("int");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.HasIndex("AgencyId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("DetectiveAgencyProject.Models.Detective", b =>
                {
                    b.Property<int>("DetectiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetectiveId"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("int");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DetectiveId");

                    b.HasIndex("AgencyId");

                    b.ToTable("Detectives");
                });

            modelBuilder.Entity("DetectiveAgencyProject.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<int?>("CaseId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DetectiveId")
                        .HasColumnType("int");

                    b.Property<int?>("DetectiveId1")
                        .HasColumnType("int");

                    b.Property<string>("Progress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.HasIndex("CaseId");

                    b.HasIndex("CaseId1");

                    b.HasIndex("DetectiveId");

                    b.HasIndex("DetectiveId1");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DetectiveAgencyProject.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<int?>("CaseId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DetectiveId")
                        .HasColumnType("int");

                    b.Property<int?>("DetectiveId1")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("CaseId");

                    b.HasIndex("CaseId1");

                    b.HasIndex("DetectiveId");

                    b.HasIndex("DetectiveId1");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("DetectiveAgencyProject.Models.Case", b =>
                {
                    b.HasOne("DetectiveAgencyProject.Models.Client", null)
                        .WithMany("Cases")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DetectiveAgencyProject.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId1");

                    b.HasOne("DetectiveAgencyProject.Models.Detective", null)
                        .WithMany("Cases")
                        .HasForeignKey("DetectiveId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DetectiveAgencyProject.Models.Detective", "Detective")
                        .WithMany()
                        .HasForeignKey("DetectiveId1");

                    b.Navigation("Client");

                    b.Navigation("Detective");
                });

            modelBuilder.Entity("DetectiveAgencyProject.Models.Client", b =>
                {
                    b.HasOne("DetectiveAgencyProject.Models.Agency", null)
                        .WithMany("Clients")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DetectiveAgencyProject.Models.Detective", b =>
                {
                    b.HasOne("DetectiveAgencyProject.Models.Agency", null)
                        .WithMany("Detectives")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DetectiveAgencyProject.Models.Order", b =>
                {
                    b.HasOne("DetectiveAgencyProject.Models.Case", null)
                        .WithMany("Orders")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DetectiveAgencyProject.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId1");

                    b.HasOne("DetectiveAgencyProject.Models.Detective", null)
                        .WithMany("Orders")
                        .HasForeignKey("DetectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DetectiveAgencyProject.Models.Detective", "Detective")
                        .WithMany()
                        .HasForeignKey("DetectiveId1");

                    b.Navigation("Case");

                    b.Navigation("Detective");
                });

            modelBuilder.Entity("DetectiveAgencyProject.Models.Report", b =>
                {
                    b.HasOne("DetectiveAgencyProject.Models.Case", null)
                        .WithMany("Reports")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DetectiveAgencyProject.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId1");

                    b.HasOne("DetectiveAgencyProject.Models.Detective", null)
                        .WithMany("Reports")
                        .HasForeignKey("DetectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DetectiveAgencyProject.Models.Detective", "Detective")
                        .WithMany()
                        .HasForeignKey("DetectiveId1");

                    b.Navigation("Case");

                    b.Navigation("Detective");
                });

            modelBuilder.Entity("DetectiveAgencyProject.Models.Agency", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Detectives");
                });

            modelBuilder.Entity("DetectiveAgencyProject.Models.Case", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("DetectiveAgencyProject.Models.Client", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("DetectiveAgencyProject.Models.Detective", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Orders");

                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
